# coding: utf-8

"""
    SteamTrades API

    API Explorer for SteamTrades' RESTful API.

    OpenAPI spec version: 1.0
    Contact: devs@steamtrad.es
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Item(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, asset_id=None, category=None, locked=None, lock_reason=None, steam_class_id=None, steam_instance_id=None):
        """
        Item - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'asset_id': 'str',
            'category': 'ItemCategory',
            'locked': 'bool',
            'lock_reason': 'str',
            'steam_class_id': 'str',
            'steam_instance_id': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'asset_id': 'asset_id',
            'category': 'category',
            'locked': 'locked',
            'lock_reason': 'lock_reason',
            'steam_class_id': 'steam_class_id',
            'steam_instance_id': 'steam_instance_id'
        }

        self._id = id
        self._asset_id = asset_id
        self._category = category
        self._locked = locked
        self._lock_reason = lock_reason
        self._steam_class_id = steam_class_id
        self._steam_instance_id = steam_instance_id

    @property
    def id(self):
        """
        Gets the id of this Item.
        Our item ID used to identify the item on all of our API endpoints

        :return: The id of this Item.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Item.
        Our item ID used to identify the item on all of our API endpoints

        :param id: The id of this Item.
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def asset_id(self):
        """
        Gets the asset_id of this Item.
        Current Steam asset ID of this item. Changes in trades.

        :return: The asset_id of this Item.
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """
        Sets the asset_id of this Item.
        Current Steam asset ID of this item. Changes in trades.

        :param asset_id: The asset_id of this Item.
        :type: str
        """
        if asset_id is None:
            raise ValueError("Invalid value for `asset_id`, must not be `None`")

        self._asset_id = asset_id

    @property
    def category(self):
        """
        Gets the category of this Item.
        Item category this item belongs to

        :return: The category of this Item.
        :rtype: ItemCategory
        """
        return self._category

    @category.setter
    def category(self, category):
        """
        Sets the category of this Item.
        Item category this item belongs to

        :param category: The category of this Item.
        :type: ItemCategory
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")

        self._category = category

    @property
    def locked(self):
        """
        Gets the locked of this Item.
        `true` if the item is locked, else `false` 

        :return: The locked of this Item.
        :rtype: bool
        """
        return self._locked

    @locked.setter
    def locked(self, locked):
        """
        Sets the locked of this Item.
        `true` if the item is locked, else `false` 

        :param locked: The locked of this Item.
        :type: bool
        """
        if locked is None:
            raise ValueError("Invalid value for `locked`, must not be `None`")

        self._locked = locked

    @property
    def lock_reason(self):
        """
        Gets the lock_reason of this Item.
        `active_trade` is encountered when the item is currently subject of an active trade. The kind of circumstances required to cause an `admin` lock are extremely rare and notifications are sent to our staff. If an item is admin-locked for a longer duration, please contact our support. `disabled_bot` may occurr if there are temporary problems with the bot holding the item. 

        :return: The lock_reason of this Item.
        :rtype: str
        """
        return self._lock_reason

    @lock_reason.setter
    def lock_reason(self, lock_reason):
        """
        Sets the lock_reason of this Item.
        `active_trade` is encountered when the item is currently subject of an active trade. The kind of circumstances required to cause an `admin` lock are extremely rare and notifications are sent to our staff. If an item is admin-locked for a longer duration, please contact our support. `disabled_bot` may occurr if there are temporary problems with the bot holding the item. 

        :param lock_reason: The lock_reason of this Item.
        :type: str
        """
        allowed_values = ["not_locked", "active_trade", "admin", "disabled_bot"]
        if lock_reason not in allowed_values:
            raise ValueError(
                "Invalid value for `lock_reason` ({0}), must be one of {1}"
                .format(lock_reason, allowed_values)
            )

        self._lock_reason = lock_reason

    @property
    def steam_class_id(self):
        """
        Gets the steam_class_id of this Item.
        Steam item class ID

        :return: The steam_class_id of this Item.
        :rtype: str
        """
        return self._steam_class_id

    @steam_class_id.setter
    def steam_class_id(self, steam_class_id):
        """
        Sets the steam_class_id of this Item.
        Steam item class ID

        :param steam_class_id: The steam_class_id of this Item.
        :type: str
        """
        if steam_class_id is None:
            raise ValueError("Invalid value for `steam_class_id`, must not be `None`")

        self._steam_class_id = steam_class_id

    @property
    def steam_instance_id(self):
        """
        Gets the steam_instance_id of this Item.
        Steam item instance ID

        :return: The steam_instance_id of this Item.
        :rtype: str
        """
        return self._steam_instance_id

    @steam_instance_id.setter
    def steam_instance_id(self, steam_instance_id):
        """
        Sets the steam_instance_id of this Item.
        Steam item instance ID

        :param steam_instance_id: The steam_instance_id of this Item.
        :type: str
        """
        if steam_instance_id is None:
            raise ValueError("Invalid value for `steam_instance_id`, must not be `None`")

        self._steam_instance_id = steam_instance_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Item):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
