# coding: utf-8

"""
    SteamTrades API

    API Explorer for SteamTrades' RESTful API.

    OpenAPI spec version: 1.0
    Contact: devs@steamtrad.es
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UserInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, steam_id=None, username=None, avatar_url=None):
        """
        UserInfo - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'steam_id': 'str',
            'username': 'str',
            'avatar_url': 'str'
        }

        self.attribute_map = {
            'steam_id': 'steam_id',
            'username': 'username',
            'avatar_url': 'avatar_url'
        }

        self._steam_id = steam_id
        self._username = username
        self._avatar_url = avatar_url

    @property
    def steam_id(self):
        """
        Gets the steam_id of this UserInfo.
        64-bit Steam ID

        :return: The steam_id of this UserInfo.
        :rtype: str
        """
        return self._steam_id

    @steam_id.setter
    def steam_id(self, steam_id):
        """
        Sets the steam_id of this UserInfo.
        64-bit Steam ID

        :param steam_id: The steam_id of this UserInfo.
        :type: str
        """
        if steam_id is None:
            raise ValueError("Invalid value for `steam_id`, must not be `None`")

        self._steam_id = steam_id

    @property
    def username(self):
        """
        Gets the username of this UserInfo.
        Currently set display name

        :return: The username of this UserInfo.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """
        Sets the username of this UserInfo.
        Currently set display name

        :param username: The username of this UserInfo.
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")

        self._username = username

    @property
    def avatar_url(self):
        """
        Gets the avatar_url of this UserInfo.
        Avatar URL (max. resolution)

        :return: The avatar_url of this UserInfo.
        :rtype: str
        """
        return self._avatar_url

    @avatar_url.setter
    def avatar_url(self, avatar_url):
        """
        Sets the avatar_url of this UserInfo.
        Avatar URL (max. resolution)

        :param avatar_url: The avatar_url of this UserInfo.
        :type: str
        """
        if avatar_url is None:
            raise ValueError("Invalid value for `avatar_url`, must not be `None`")

        self._avatar_url = avatar_url

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UserInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
